### ISSUE TITLE
Plocka in relevant data från ett kalkylark automatiskt

### ISSUE THREAD

**Issue by Samuel-Berger** [dtekcth/snd-tentastat#4]
Så slipper någon ta sig tid och sitta och skriva in det manuellt.

**Comment by Cadynum** [comment]
Detta har jag i princip gjort för ett ofärdigt projektet där jag tänkte att alla resultat på Chalmers ska vara sökbara på en webbsida. Jag kan fixa så det skriver ut det i resultat.tsv-formatet.
